export const PLANT_CONFIGURATION = {
  id: "PLANT-01",
  name: "LUMI Virtual Airport HVAC Plant",
  location: "Virtual Airport Terminal",
  simulationMode: true,
  chillerQuantity: 4,
  ratedPowerPerChillerKw: 11,
  totalRatedChillerPowerKw: 44,
  defaultChilledWaterSupplyTempC: 7,
  defaultChilledWaterReturnTempC: 12.5,
  defaultCondenserWaterEnteringTempC: 29,
  defaultCondenserWaterLeavingTempC: 34,
  simulationTickMs: 1000,
  snapshotIntervalMs: 60000,
} as const;

export const CHILLER_CONFIGURATION = [
  {
    id: "CH-01",
    name: "Water-Cooled Chiller 01",
    ratedPowerKw: 11,
    ratedCoolingCapacityKw: 52,
    designCop: 4.7,
    leadLagOrder: 1,
  },
  {
    id: "CH-02",
    name: "Water-Cooled Chiller 02",
    ratedPowerKw: 11,
    ratedCoolingCapacityKw: 52,
    designCop: 4.7,
    leadLagOrder: 2,
  },
  {
    id: "CH-03",
    name: "Water-Cooled Chiller 03",
    ratedPowerKw: 11,
    ratedCoolingCapacityKw: 52,
    designCop: 4.7,
    leadLagOrder: 3,
  },
  {
    id: "CH-04",
    name: "Water-Cooled Chiller 04",
    ratedPowerKw: 11,
    ratedCoolingCapacityKw: 52,
    designCop: 4.7,
    leadLagOrder: 4,
  },
] as const;

export const AHU_CONFIGURATION = [
  {
    id: "AHU-01",
    name: "Check-in Hall AHU",
    zoneId: "ZONE-CHECKIN",
    zoneName: "Check-in Hall",
    designAirflowCmh: 18000,
    designFanPowerKw: 7.5,
    normalSetpointC: 23,
    designOccupancy: 500,
  },
  {
    id: "AHU-02",
    name: "Departure Hall AHU",
    zoneId: "ZONE-DEPARTURE",
    zoneName: "Departure Hall",
    designAirflowCmh: 20000,
    designFanPowerKw: 8.5,
    normalSetpointC: 22.5,
    designOccupancy: 700,
  },
  {
    id: "AHU-03",
    name: "Arrival Hall AHU",
    zoneId: "ZONE-ARRIVAL",
    zoneName: "Arrival Hall",
    designAirflowCmh: 19500,
    designFanPowerKw: 8.2,
    normalSetpointC: 23,
    designOccupancy: 650,
  },
  {
    id: "AHU-04",
    name: "Baggage Claim AHU",
    zoneId: "ZONE-BAGGAGE",
    zoneName: "Baggage Claim",
    designAirflowCmh: 16000,
    designFanPowerKw: 6.8,
    normalSetpointC: 23.5,
    designOccupancy: 450,
  },
  {
    id: "AHU-05",
    name: "VIP Lounge AHU",
    zoneId: "ZONE-VIP",
    zoneName: "VIP Lounge",
    designAirflowCmh: 8000,
    designFanPowerKw: 3.5,
    normalSetpointC: 22,
    designOccupancy: 120,
  },
  {
    id: "AHU-06",
    name: "Immigration Hall AHU",
    zoneId: "ZONE-IMMIGRATION",
    zoneName: "Immigration Hall",
    designAirflowCmh: 15000,
    designFanPowerKw: 6.2,
    normalSetpointC: 23,
    designOccupancy: 400,
  },
] as const;
